window.translations = {
    ar: {
        brand_name: "حرفي.ma",
        brand_title: "خدمة الحرفيين المغاربة",
        brand_subtitle: "منصة تواصل الحرفي مع العميل",
        nav_home: "الرئيسية",
        nav_search: "البحث عن حرفي",
        nav_register: "تسجيل حرفي",
        nav_contact: "اتصل بنا",
        nav_login: "تسجيل الدخول",
        nav_signup: "تسجيل جديد",
        hero_title: '<span class="text-primary">أفضل الحرفيين</span> المغاربة في خدمتك',
        hero_subtitle: "أكثر من حرفي محترف في جميع أنحاء المملكة المغربية ينتظرون لمساعدتك في إنجاز أعمالك بجودة عالية وأسعار مناسبة",
        hero_btn_search: "ابحث عن حرفي",
        hero_btn_register: "سجل كمحترف",
        hero_btn_client_register: "التسجيل كعميل",
        hero_badge: "حرفيون معتمدون وموثوقون",
        quick_search_title: "ابحث عن حرفي في مدينتك",
        quick_search_service_label: "ما نوع الخدمة التي تبحث عنها؟",
        quick_search_service_select: "اختر المهنة",
        quick_search_city_label: "المدينة",
        quick_search_city_select: "اختر المدينة",
        quick_search_btn: "ابحث",
        professions_title: "تصفح المهن الرئيسية",
        professions_subtitle: "اختر المهارة المطلوبة وتواصل مباشرة مع الحرفيين المحترفين",
        p_carpenter_title: "نجارة",
        p_carpenter_desc: "تصميم وتركيب وإصلاح الأثاث والأبواب والنوافذ والمنتجات الخشبية بدقة وعناية.",
        p_plumber_title: "سباكة",
        p_plumber_desc: "حل جميع مشاكل تسربات المياه، تصريف المياه، تركيب وصيانة شبكات المياه والصرف الصحي.",
        p_electrician_title: "كهرباء",
        p_electrician_desc: "تأسيس وصيانة الشبكات الكهربائية للمنازل، تركيب الإضاءة وحل جميع الأعطال بأمان كامل.",
        p_painter_title: "صباغة",
        p_painter_desc: "تنفيذ أحدث أعمال الدهانات والديكورات الداخلية والخارجية بجودة عالية وألوان متناسقة.",
        p_mason_title: "بناء",
        p_mason_desc: "ترميم، بناء، تلييس وجميع أعمال المقاولات العامة للمباني والأسوار بدقة واحترافية.",
        p_blacksmith_title: "حدادة",
        p_blacksmith_desc: "جميع أعمال تشكيل المعادن، البوابات، الدرابزين والحواجز المعدنية بتصاميم حديثة وقوية.",
        p_tailor_title: "خياطة",
        p_tailor_desc: "خياطة الملابس التقليدية والمودرن وتفصيل حسب الطلب مع تسليم سريع وجودة تشطيب.",
        p_mechanic_title: "صيانة السيارات",
        p_mechanic_desc: "تشخيص وإصلاح أعطال محركات السيارات، كهرباء وميكانيك السيارات تحت إشراف خبراء.",
        stat_craftsmen: "حرفي مسجل",
        stat_cities: "مدينة مغربية",
        stat_completed: "مشروع مكتمل",
        stat_rating: "نسبة رضا العملاء",
        how_it_works_title: "كيف تعمل المنصة",
        step_1_title: "ابحث عن حرفي",
        step_1_desc: "اختر المهنة والمدينة لتصفح مئات الحرفيين المتوفرين في منطقتك بالقرب منك.",
        step_2_title: "قارن الملفات والتقييمات",
        step_2_desc: "راجع تفاصيل الملف الشخصي لكل حرفي، سنوات الخبرة، معرض الأعمال وتقييمات العملاء.",
        step_3_title: "تواصل مباشرة وابدأ العمل",
        step_3_desc: "اتصل مباشرة بالهاتف أو تواصل عبر واتساب للاتفاق على التفاصيل وبدء مشروعك بكل أمان.",
        trust_section_title: "لماذا تختار منصتنا؟",
        trust_1_title: "أمان وموثوقية",
        trust_1_desc: "يتم التحقق من هوية وخبرة الحرفيين المسجلين لضمان المصداقية.",
        trust_2_title: "تواصل مباشر مجاني",
        trust_2_desc: "تواصل مباشرة مع الحرفيين بدون أي وسطاء أو رسوم خفية إضافية.",
        trust_3_title: "تقييمات حقيقية",
        trust_3_desc: "تقييمات شفافة وموثوقة من عملاء حقيقيين جربوا خدمات الحرفيين بالفعل.",
        reviews_title: "ماذا يقول عملاؤنا؟",
        reviews_subtitle: "آراء وتقييمات حقيقية من عملائنا الذين تعاملوا مع محترفينا في مختلف المدن",
        footer_desc: "منصة رائدة في الربط بين الحرفيين المحترفين والعملاء في جميع أنحاء المملكة المغربية منذ 2026",
        footer_links_title: "روابط سريعة",
        footer_cities_title: "المدن الرئيسية",
        footer_newsletter_title: "النشرة البريدية",
        footer_newsletter_desc: "اشترك في نشرتنا البريدية لتصلك آخر العروض والخدمات الجديدة",
        footer_newsletter_placeholder: "بريدك الإلكتروني",
        footer_newsletter_notice: "نحن نحترم خصوصيتك. لن نشارك بريدك مع أي طرف ثالث.",
        copyright_text: "جميع الحقوق محفوظة. منصة الحرفيين المغاربة 2026.",
        search_hero_title: "ابحث عن حرفي",
        search_skill_filter: "المهنة",
        search_skill_placeholder: "اختر المهارة",
        search_city_filter: "المدينة",
        search_city_placeholder: "كل المدن",
        search_rating_filter: "أدنى تقييم",
        search_rating_placeholder: "كل التقييمات",
        search_btn_text: "ابحث",
        search_clear_filters: "مسح الفلاتر",
        search_loading: "جارٍ تحميل النتائج...",
        search_no_results: "لم يتم العثور على حرفيين يطابقون معايير البحث.",
        search_experience: "سنوات خبرة",
        search_view_profile: "عرض الملف الشخصي",
        search_contact_phone: "اتصل بالهاتف",
        search_verified: "موثوق",
        search_featured: "مميز",
        profile_back_to_search: "العودة للبحث",
        profile_skills_title: "المهارات والخبرات",
        profile_portfolio_title: "معرض الأعمال والورشات",
        profile_contact_title: "معلومات الاتصال المباشر",
        profile_reviews_title: "مراجعات العملاء",
        profile_no_reviews: "لا توجد مراجعات أو تقييمات لهذا الحرفي بعد.",
        login_title: "دخول الحرفي",
        login_subtitle: "قم بتسجيل الدخول للوصول إلى لوحة التحكم الخاصة بك",
        login_email_label: "البريد الإلكتروني",
        login_email_placeholder: "example@email.com",
        login_code_label: "كود الحرفي",
        login_code_placeholder: "CRAFT261549",
        login_code_hint: "أدخل البريد الإلكتروني أو كود الحرفي",
        login_password_label: "كلمة المرور",
        login_password_placeholder: "••••••••",
        login_or: "أو",
        login_error_missing: "يرجى إدخال البريد الإلكتروني أو كود الحرفي",
        login_error_password: "يرجى إدخال كلمة المرور",
        login_success: "تم الدخول بنجاح ✅",
        login_error_invalid: "بيانات الدخول غير صحيحة",
        login_error_network: "حدث خطأ في الاتصال. حاول مرة أخرى.",
        login_identifier_label: "البريد الإلكتروني أو كود الحرفي",
        login_identifier_placeholder: "example@email.com أو CRAFT261549",
        login_password_label: "كلمة المرور",
        login_password_placeholder: "أدخل كلمة المرور",
        login_remember: "تذكرني",
        login_forgot: "نسيت كلمة المرور؟",
        login_btn: "دخول",
        login_gmail: "الدخول عبر Gmail",
        login_gmail_soon: "سيتم تفعيل تسجيل الدخول عبر Gmail قريباً",
        login_no_account: "ليس لديك حساب؟",
        login_signup_link: "اضغط هنا لتسجيل حرفي جديد",
        login_welcome: "مرحباً بك",
        register_title: "تسجيل حرفي جديد",
        register_subtitle: "املأ البيانات أدناه لإنشاء حسابك الاحترافي",
        register_info_title: "تسجيل سهل وآمن",
        register_info_desc: "انضم إلى شبكة الحرفيين المحترفين. أنشئ ملفك الشخصي لعرض خبراتك ومحفظة أعمالك وزيادة فرص الحصول على عمل.",
        register_step1: "البيانات الشخصية",
        register_step2: "المهنة",
        register_step3: "الصور والمراجعة",
        register_nav_home: "الرئيسية",
        register_nav_login: "دخول الحرفي",
        contact_title: "اتصل بالإدارة",
        contact_subtitle: "عمّر المعلومات ديالك وصيفط سؤالك، وغادي يوصلك الرد من الإدارة.",
        contact_name: "الاسم الكامل",
        contact_type: "نوعك",
        contact_type_guest: "زائر",
        contact_type_craftsman: "حرفي",
        contact_type_client: "زبون",
        contact_phone: "رقم الهاتف",
        contact_subject: "الموضوع (اختياري)",
        contact_message: "الرسالة",
        contact_message_placeholder: "اكتب سؤالك أو استفسارك هنا...",
        contact_send_btn: "إرسال الرسالة للإدارة",
        contact_back: "رجوع للرئيسية",
        contact_admin_chat: "دخول لشات الإدارة (للمسجلين)",
        contact_about_title: "من نحن",
        contact_about_text: "منصة Hirafi.ma تربط بين الحرفيين المغاربة والزوار الباحثين عن خدمات موثوقة. هدفنا تنظيم التواصل، إبراز الحرفيين، وتسهيل الدعم عبر نظام مراسلة آمن.",
        contact_confirm_login: "خاصك تسجل الدخول باش تراسل الإدارة. واش نمشيو لصفحة تسجيل الدخول؟",
        contact_send_success: "تم إرسال الرسالة بنجاح",
        contact_send_error: "فشل إرسال الرسالة",
        contact_conn_error: "وقع مشكل فالربط، حاول مرة أخرى.",
        admin_login_title: "🔐 دخول الإدارة",
        admin_login_badge_title: "🔒 منطقة محمية",
        admin_login_badge_desc: "وصول آمن حصراً على مدير النظام",
        admin_login_email: "البريد الإلكتروني",
        admin_login_password: "كلمة المرور",
        admin_login_remember: "تذكرني على هذا الجهاز",
        admin_login_btn: "دخول آمن",
        admin_dashboard_title: "لوحة التحكم",
        admin_brand_title: "لوحة التحكم",
        admin_feat1_title: "إدارة الحرفيين",
        admin_feat1_desc: "إضافة وتعديل وحذف بيانات الحرفيين",
        forgot_title: "نسيت كلمة المرور",
        forgot_desc: "أدخل بريدك الإلكتروني لنرسل لك رابط إعادة تعيين كلمة المرور.",
        forgot_btn: "إرسال رابط إعادة التعيين",
        forgot_back: "← العودة لتسجيل الدخول",
        nav_blog: "المدونة",
        nav_faq: "الأسئلة الشائعة",
        nav_cities: "المدن",
        cities_hero_title: "مدن رئيسية، تخصصات مختلفة، وتجربة بحث أوضح حسب كل منطقة.",
        cities_discover: "اكتشف المدينة",
        faq_hero_title: "أجوبة سريعة وواضحة",
        blog_hero_title: "المدونة اللي كتقرّبك من الحرفي المناسب وتساعدك تاخذ قرار واثق.",
        idx_prof_carpentry: "نجارة",
        idx_prof_plumbing: "سباكة",
        idx_prof_electricity: "كهرباء",
        idx_prof_building: "بناء",
        idx_prof_painting: "صباغة",
        idx_prof_blacksmith: "حدادة",
        idx_prof_tailoring: "خياطة",
        idx_prof_design: "تصميم",
        idx_prof_photography: "تصوير",
        idx_prof_cooking: "الطبخ",
        idx_prof_farming: "زراعة",
        idx_prof_events: "تنظيم الحفلات",
        idx_prof_mechanic: "صيانة السيارات",
        idx_prof_other: "حرف اخرى",
        idx_regions_major: "الجهات الكبرى",
        idx_regions_other: "مدن أخرى",
        idx_city_casablanca: "الدار البيضاء",
        idx_city_rabat: "الرباط",
        idx_city_fes: "فاس",
        idx_city_marrakech: "مراكش",
        idx_city_chichaoua: "شيشاوة",
        idx_city_tangier: "طنجة",
        idx_city_meknes: "مكناس",
        idx_city_agadir: "أكادير",
        idx_city_tetouan: "تطوان",
        idx_city_oujda: "وجدة",
        idx_city_kenitra: "القنيطرة",
        idx_city_mohammedia: "المحمدية",
        idx_city_beni_mellal: "بني ملال",
        idx_city_safi: "آسفي",
        idx_city_eljadida: "الجديدة",
        idx_city_taza: "تازة",
        idx_city_larache: "العرائش",
        idx_city_khouribga: "خريبكة",
        idx_city_temara: "تمارة",
        idx_city_sale: "سلا",
        idx_city_benguerir: "بن جرير",
        idx_city_ouarzazate: "ورزازات",
        idx_city_dakhla: "الداخلة",
        idx_city_laayoune: "العيون",
        idx_popular_jobs_title: "مهن شائعة:",
        idx_job_carpenter: "نجار",
        idx_job_plumber: "سباك",
        idx_job_electrician: "كهربائي",
        idx_job_painter: "دهان",
        idx_job_builder: "بناء",
        idx_job_mechanic: "ميكانيكي",
        idx_prof_card1_title: "نجارة وأثاث",
        idx_prof_card1_desc: "تصميم وتصنيع وتركيب الأثاث المنزلي والمكتبي",
        idx_prof_card1_stat1: "320+ حرفي",
        idx_prof_card1_link: "تصفح النجارين",
        idx_prof_card2_title: "سباكة وصرف صحي",
        idx_prof_card2_desc: "تركيب وإصلاح أنابيب المياه والصرف الصحي",
        idx_prof_card2_stat1: "280+ حرفي",
        idx_prof_card2_link: "تصفح السباكين",
        idx_prof_card3_title: "كهرباء منزلية",
        idx_prof_card3_desc: "تركيب وإصلاح الدوائر الكهربائية والإنارة",
        idx_prof_card3_stat1: "350+ حرفي",
        idx_prof_card3_link: "تصفح الكهربائيين",
        idx_prof_card4_title: "بناء وتشييد",
        idx_prof_card4_desc: "بناء وتجديد المنازل والعمارات والمنشآت",
        idx_prof_card4_stat1: "420+ حرفي",
        idx_prof_card4_link: "تصفح البنائين",
        idx_step_subtitle: "3 خطوات بسيطة للحصول على خدمة مميزة",
        idx_featured_title: "حرفيون مميزون",
        idx_featured_subtitle: "تعرف على أفضل الحرفيين ذوي التقييمات العالية في منصتنا",
        idx_feat_badge_req: "الأكثر طلباً",
        idx_feat_badge_fast: "الأسرع استجابة",
        idx_feat_badge_top: "الأعلى تقييماً",
        idx_feat_badge_exp: "خبير معتمد",
        idx_feat_prof_carp: "نجار محترف",
        idx_feat_prof_elec: "كهربائي منزلي",
        idx_feat_prof_plumb: "سباك محترف",
        idx_feat_prof_build: "بناء ومقاول",
        idx_feat_review_1: "(128 تقييم)",
        idx_feat_review_2: "(94 تقييم)",
        idx_feat_review_3: "(76 تقييم)",
        idx_feat_review_4: "(203 تقييم)",
        idx_feat_exp_12: "خبرة: 12 سنة",
        idx_feat_exp_8: "خبرة: 8 سنوات",
        idx_feat_exp_15: "خبرة: 15 سنة",
        idx_feat_exp_20: "خبرة: 20 سنة",
        idx_feat_btn_view: "عرض الملف",
        idx_cta_title: "هل أنت حرفي محترف؟",
        idx_cta_text: "انضم إلى منصتنا وزد من فرص عملك مع آلاف العملاء المحتملين في جميع أنحاء المملكة المغربية",
        idx_cta_feat1: "وصول إلى آلاف العملاء الجدد",
        idx_cta_feat2: "ملف شخصي احترافي مع معرض أعمال",
        idx_cta_feat3: "تقييمات ومراجعات تعزز مصداقيتك",
        idx_cta_feat4: "إدارة سهلة للطلبات والمحادثات",
        idx_cta_btn1: "سجل كمحترف الآن",
        idx_cta_btn2: "كيف يعمل النظام؟",
        idx_trust_sub: "منصة موثوقة بآلاف الحرفيين المعتمدين والموثوقين في جميع أنحاء المملكة المغربية",
        idx_trust_t1: "حرفيون معتمدون",
        idx_trust_d1: "جميع الحرفيين يخضعون لعملية توثيق ومطابقة هوية قبل الانضمام للمنصة",
        idx_trust_t2: "دفع آمن",
        idx_trust_d2: "نظام دفع آمن ومضمون. نقوم بتوفير بيئة موثوقة لجميع المعاملات",
        idx_trust_t3: "دعم 24/7",
        idx_trust_d3: "فريق الدعم متوفر على مدار الساعة لمساعدتك في أي وقت",
        idx_trust_t4: "ضمان استرداد",
        idx_trust_d4: "ضمان استرداد الأموال خلال 48 ساعة إذا لم تكن راضياً عن الخدمة",
        idx_rev_sub: "ما يقوله عملاؤنا عن تجربتهم مع منصتنا",
        idx_rev_t1: "\"وجدت نجار ممتاز في الدار البيضاء، تعامل مميز والأثاث صُنع بجودة عالية. شكراً لمنصتكم المميزة\"",
        idx_rev_t2: "\"الكهربائي الذي تواصلت معه كان محترفاً جداً، أنجز العمل في الموعد المحدد وبأسعار معقولة\"",
        idx_rev_t3: "\"توصيل سهل وسريع، والسباك كان على أتم الاحترام والمهنية. أنصح الجميع بالتجربة\"",
        idx_stat_title: "إحصائيات النجاح",
        idx_stat_sub: "من أرقامنا، نجاحكم هو فخرنا",
        idx_footer_terms: "شروط الاستخدام",
        idx_footer_privacy: "سياسة الخصوصية",
        idx_footer_cookies: "سياسة ملفات تعريف الارتباط",
        // Artisan Showcase Carousel
        showcase_eyebrow: "حرفيون معتمدون وموثوقون",
        showcase_title_1: "اكتشف أفضل الحرفيين",
        showcase_title_2: "وأعمالهم المميزة",
        showcase_subtitle: "نماذج حقيقية من أعمال الحرفيين المحترفين في شتى التخصصات — جودة استثنائية وخبرة موثوقة",
        showcase_btn_view: "عرض الملف",
        prof_carpenter: "نجارة",
        prof_plumber: "سباكة",
        prof_electrician: "كهرباء",
        prof_painter: "دهان",
        prof_welder: "حدادة",
        prof_tailor: "خياطة",
        prof_decorator: "ديكور",
        prof_traditional: "صنائع تقليدية",
        showcase_serv_carpenter: "تصميم وتنفيذ أثاث خشبي عصري وتقليدي",
        showcase_serv_plumber: "إصلاح وتركيب أنظمة السباكة والمياه",
        showcase_serv_electrician: "تركيب وصيانة الشبكات الكهربائية",
        showcase_serv_painter: "طلاء وزخرفة الجدران بتقنيات تقليدية وعصرية",
        showcase_serv_welder: "تصنيع أبواب ونوافذ حديدية بأنماط مغربية",
        showcase_serv_tailor: "تفصيل جلابيب وقفاطين بطراز مغربي أصيل",
        showcase_serv_decorator: "تصميم وزخرفة داخلية بأسلوب مغربي معاصر",
        showcase_serv_traditional: "زليج ونقش وأعمال تراثية مغربية أصيلة",
        // Gallery Section
        gallery_plumber_title: "سباكة محترفة",
        gallery_plumber_desc: "إصلاح سريع ودقيق لجميع أنظمة المياه",
        gallery_electrician_title: "كهرباء منزلية",
        gallery_electrician_desc: "تركيب وصيانة الدوائر الكهربائية بأمان تام",
        gallery_carpenter_title: "نجارة فاخرة",
        gallery_carpenter_desc: "تصميم الأثاث الخشبي وفق أعلى المعايير",
        gallery_painter_title: "دهان احترافي",
        gallery_painter_desc: "تشطيبات ألوان أنيقة لجدران عصرية",
        gallery_welder_title: "لحام دقيق",
        gallery_welder_desc: "تجميعات معدنية قوية بجودة عالية",
        // Digital Platform Section
        digital_platform_badge: "منصة رقمية للحرفيين",
        digital_platform_title: "جرب منصة حرفية تقدم تجربة عالمية",
        digital_platform_subtitle: "بحث ذكي، تقييمات حقيقية، حجز ثابت ودعم محلي؛ كل ذلك في واجهة نظيفة وسريعة تشعر بها مثل أكبر المنصات العالمية.",
        digital_platform_search_title: "بحث ذكي وسريع",
        digital_platform_search_desc: "استخدم الفلترة حسب المدينة والمهنة لعرض النتائج الأكثر دقة بسرعة.",
        digital_platform_profiles_title: "ملفات موثوقة",
        digital_platform_profiles_desc: "حرفيون مع تقييمات وصور واضحة ومعلومات كاملة تضمن اختيارك بثقة.",
        digital_platform_booking_title: "حجز آمن وسهل",
        digital_platform_booking_desc: "جدولة الخدمة والتواصل مع الحرفي بطريقة واضحة ومرنة.",
        digital_platform_support_title: "دعم محلي مباشر",
        digital_platform_support_desc: "فريقنا جاهز للرد على أسئلتك وإرشادك لتحقيق الخدمة الأفضل.",
        digital_platform_btn: "ابدأ بحثك الآن",
        brand_short_title: "حرفي.ما",
        trust_subtitle: "منصة موثوقة بآلاف الحرفيين المعتمدين في جميع أنحاء المملكة المغربية",
        loading_text: "جارٍ التحقق من البيانات...",
        manual_skill_placeholder: "أو اكتب المهنة يدوياً",
        manual_city_placeholder: "أو اكتب المدينة يدوياً",
        load_more: "عرض المزيد",
        no_results: "لم يتم العثور على نتائج",
        copyright_ar: "جميع الحقوق محفوظة. منصة الحرفيين المغاربة 2026.",
        login_brand: "الحرفي",
        login_brand_subtitle: "منصة الحرفيين",
        login_nav_signup: "تسجيل جديد",
        login_info_title: "مرحباً بك",
        login_benefit1: "حماية بياناتك وخصوصيتك",
        login_benefit2: "واجهة سهلة الاستخدام",
        login_benefit3: "عرض محفظة الأعمال وشهادات الخبرة",
        login_benefit4: "انضم لمجتمع الحرفيين المغاربة",
        login_benefit5: "زد من فرص حصولك على العملاء",
        profile_not_found: "الحرفي غير موجود",
        profile_not_found_desc: "عذراً، لم يتم العثور على هذا الحرفي",
        profile_btn_search: "بحث عن حرفيين",
        profile_contact_now: "تواصل الآن",
        profile_whatsapp: "واتساب",
        profile_no_portfolio: "لا تتوفر أعمال سابقة حالياً",
        profile_loading: "جارٍ تحميل الملف...",
        profile_section_desc: "الوصف",
        profile_section_bio: "نبذة عن الحرفي",
        profile_section_skills: "المهارات",
        profile_section_portfolio: "أعمال سابقة",
        profile_section_contact: "معلومات التواصل",
        profile_section_admin_chat: "مراسلة الإدارة",
        profile_admin_chat_desc: "إذا كنت حرفي وتحتاج تتواصل مع الإدارة، استعمل الشات المحلي باش تصيفط رسالتك وتتبع الردود.",
        profile_admin_chat_btn: "افتح شات الإدارة",
        search_results_summary: "عرض ${count} من أصل ${total} حرفي",
        cities_brand_text: "خدمة الحرفيين المغاربة",
        cities_hero_subtitle: "من الدار البيضاء حتى أكادير، المنصة كتركز على إبراز الحرفيين الأقرب ليك حسب المدينة والتخصص.",
        cities_section_title: "نظرة سريعة على المدن",
        cities_section_desc: "كل بطاقة كتعطيك لمحة على طابع الطلب والتخصصات الأكثر حضوراً، ومن بعدها تقدر تمشي مباشرة للبحث المفلتر.",
        cities_detail_title: "تفاصيل كل مدينة",
        cities_detail_desc: "محتوى مختصر يعطيك انطباع عملي على التخصصات المطلوبة، طبيعة الزبناء، وأفضل طريقة تبدأ بها البحث داخل كل مدينة.",
        cities_footer_text: "© 2026 خدمة الحرفيين المغاربة - تغطية محلية بطابع premium.",
        blog_brand_text: "خدمة الحرفيين المغاربة",
        blog_hero_subtitle: "هنا كنشاركو نصائح عملية، قصص نجاح حقيقية، وتوجيهات ذكية كتهم الزبناء والحرفيين معاً. الهدف هو نخلي التجربة فـ Hirafi.ma أوضح، أرقى، وأكثر احترافية من أول زيارة حتى نهاية المشروع.",
        blog_featured_meta: "مقال مميز | 6 دقائق قراءة",
        blog_featured_title: "كيفاش تختار حرفي محترف بدون ما تضيع الوقت أو الميزانية؟",
        blog_featured_desc: "كنشرح فيه المعايير اللي خاص تشوفها قبل أي تواصل: جودة الملف، وضوح الأعمال السابقة، سرعة الرد، وشنو هي الأسئلة اللي خاصك تطرح قبل ما تبدا الخدمة فعلاً.",
        blog_hl1: "كيف تفرّق بين الملف العادي والملف الاحترافي",
        blog_hl2: "مؤشرات كتبيّن الجدية قبل الاتفاق",
        blog_hl3: "طريقة مختصرة لتقييم الثمن مقابل الجودة",
        blog_section_title: "أحدث المقالات",
        blog_section_desc: "محتوى مرتب على شكل مواضيع عملية وسهلة التطبيق، سواء كنت زبون باغي خدمة محترمة أو حرفي باغي يطور حضوره الرقمي.",
        blog_newsletter_title: "باغي تبقى على اطلاع بآخر النصائح والفرص؟",
        blog_newsletter_desc: "خلّي لينا البريد ديالك وغادي يصلك مستجدات مختصرة ونافعة حول أفضل طرق التعامل مع الحرفيين، وتحسين البروفايل، واستغلال المنصة بشكل أذكى.",
        blog_newsletter_placeholder: "بريدك الإلكتروني",
        blog_newsletter_btn: "اشترك الآن",
        blog_insight1_title: "رؤية واضحة",
        blog_insight1_desc: "المحتوى ديالنا ماشي عام. كل مقال مكتوب باش يخدم قرار حقيقي داخل تجربة الحجز أو تقديم الخدمة.",
        blog_insight2_title: "جودة أعلى",
        blog_insight2_desc: "كنركزو على الجودة، الثقة، والتنظيم أكثر من الكلام العام. الهدف هو تجربة premium فعلاً.",
        blog_insight3_title: "خطوات قابلة للتطبيق",
        blog_insight3_desc: "كل فكرة كتخرج منها بخطوة واضحة: شنو تسول، شنو تجهز، وشحال تقارن قبل الاتفاق.",
        blog_footer_text: "© 2026 خدمة الحرفيين المغاربة - محتوى يخدم الثقة والجودة.",
        faq_brand_text: "خدمة الحرفيين المغاربة",
        faq_hero_subtitle: "كلشي اللي كيتسول عليه الزبون أو الحرفي لقا ليه جواب مرتب ومهني. جمعنا أكثر الأسئلة اللي كتوصلنا حول البحث، التسجيل، التسعير، الثقة، والمراسلة.",
        faq_support_title: "ما لقيتيش الجواب اللي كيريحك؟",
        faq_support_desc: "إلى كان عندك سؤال خاص، أو بغيتي توجيه مباشر على حالة معينة، الإدارة ديال المنصة تقدر تواكبك عبر صفحة التواصل أو مركز الرسائل.",
        faq_support_btn1: "تواصل مع الإدارة",
        faq_support_btn2: "جرب البحث الآن",
        faq_footer_text: "© 2026 خدمة الحرفيين المغاربة - أجوبة واضحة ومسار أكثر احترافية.",
        admin_feat2_title: "إدارة النقاط",
        admin_feat2_desc: "إدخال النقاط والتقارير الأكاديمية",
        admin_feat3_title: "إدارة الدروس",
        admin_feat3_desc: "إضافة ومراقبة الدروس والمحاضرات",
        admin_feat4_title: "التقارير والإحصائيات",
        admin_feat4_desc: "عرض تقارير مفصلة وإحصائيات شاملة",
        contact_email_label: "البريد الإلكتروني",
        contact_email_placeholder: "example@gmail.com",
        forgot_email_placeholder: "example@email.com",
        admin_login_email_placeholder: "admin@hirafi.ma",
        footer_home: "الرئيسية",
        footer_search: "البحث عن حرفي",
        footer_register: "سجل كحرفي",
        footer_contact: "اتصل بنا",
        footer_blog: "المدونة",
        footer_faq: "الأسئلة الشائعة",
        footer_contact_address: "مراكش، المغرب",
        showcase_review_label: "تقييم",
        showcase_serv_tailor_2: "تفصيل وتصميم ملابس حرفية مريحة وأنيقة",
        showcase_serv_decorator_2: "تهيئة وتجديد فضاءات منزلية أنيقة ومريحة",
        showcase_serv_tailor_3: "تفصيل ملابس مهنية وعبايات بتطريزات أنيقة",
        showcase_serv_electrician_2: "فحص وتركيب اللوحات الكهربائية الآمنة والمضيئة",
        showcase_serv_carpenter_2: "تصميم أثاث على المقاس وترميم قطع خشبية بلمسات دقيقة",
        footer_logo_text: "حرفي.ما",
        mp_btn_artisan: "أنا حرفي",
        mp_btn_artisan_sub: "ابحث عن مشاريع متاحة",
        mp_btn_client: "أنا عميل",
        mp_btn_client_sub: "انشر مشروعاً",
        mp_artisan_card_title: "فضاء الحرفي",
        mp_artisan_card_sub: "ابحث عن مشاريع متاحة وقدم عرضك للعمل.",
        mp_client_card_title: "فضاء العميل",
        mp_client_card_sub: "انشر مشروعاً جديداً وابحث عن حرفي مناسب.",
        mp_btn_creer_compte: "إنشاء حساب",
        mp_btn_deja_artisan: "أنا مسبقاً حرفي",
        mp_btn_deja_client: "أنا مسبقاً عميل",
        mp_eyebrow: "فرص جديدة",
        mp_title: "أحدث طلبات العملاء",
        mp_subtitle: "اكتشف أحدث المشاريع المنشورة من طرف العملاء وقدم عرضك للفوز بفرص عمل جديدة.",
        modal_artisan_space: "فضاء الحرفي",
        modal_artisan_login_tab: "أنا مسبقاً حرفي",
        modal_create_account: "إنشاء حساب",
        modal_email: "البريد الإلكتروني",
        modal_password: "كلمة المرور",
        modal_login_btn: "تسجيل الدخول",
        modal_fullname: "الاسم الكامل",
        modal_phone: "رقم الهاتف",
        modal_profession: "المهنة",
        modal_city: "المدينة",
        modal_confirm_pass: "تأكيد كلمة المرور",
        modal_terms: "أوافق على شروط الاستخدام",
        modal_register_btn: "إنشاء حسابي",
        modal_client_space: "فضاء العميل",
        modal_client_login_tab: "أنا مسبقاً عميل",
        // Client Dashboard & Workspace
        client_nav_requests: "طلبات العمل",
        client_nav_publish: "نشر طلب جديد",
        client_nav_complaints: "مركز الشكاوى",
        client_nav_profile: "تعديل الملف الشخصي",
        client_nav_logout: "تسجيل الخروج",
        client_header_requests: "طلبات العمل الخاصة بي",
        client_header_publish: "نشر طلب عمل جديد في السوق",
        client_header_complaints: "مركز الشكاوى والمخالفات",
        client_header_profile: "تعديل الملف الشخصي والمعلومات الشخصية",
        client_stat_total: "إجمالي الطلبات",
        client_stat_waiting: "طلبات تنتظر عروض",
        client_stat_inprogress: "قيد التنفيذ",
        client_stat_offers: "إجمالي العروض المستلمة",
        client_sec_published: "طلبات العمل المنشورة",
        client_loading_requests: "جاري تحميل طلباتك...",
        client_sec_proposals: "عروض الأسعار المقترحة",
        client_btn_back: "عودة",
        client_tag_waiting: "قيد الانتظار",
        client_btn_proposals: "العروض",
        client_proposal_specialty: "تخصص: ",
        client_proposal_city: "المدينة: ",
        client_proposal_rating: "التقييم: ",
        client_proposal_trust: "الموثوقية: ",
        client_proposal_exp: "الخبرة: ",
        client_proposal_years: "سنوات",
        client_proposal_duration: "المدة: ",
        client_status_accepted: "مقبول",
        client_btn_accept: "قبول وتواصل",
        client_form_title: "عنوان العمل أو الخدمة *",
        client_form_category: "نوع الخدمة أو الفئة *",
        client_form_preference: "تفضيل الاتصال *",
        client_form_description: "شرح مفصل للعمل المطلوب *",
        client_btn_next: "المتابعة",
        client_btn_prev: "السابق",
        client_form_media_lbl: "أرفق صوراً فوتوغرافية واضحة للمشكلة أو موقع العمل",
        client_form_media_drag: "اسحب وأفلت الصور هنا أو اضغط للاختيار",
        client_form_media_hint: "يمكنك اختيار عدة صور أو فيديوهات كحد أقصى (JPG, PNG, WEBP, MP4)",
        client_form_city: "المدينة *",
        client_form_neighborhood: "الحي أو المنطقة",
        client_form_gps: "إرفاق الموقع الجغرافي (جي بي اس)",
        client_form_gps_btn: "تحديد موقعي الحالي",
        client_form_gps_status: "لم يتم تحديد الإحداثيات",
        client_form_budget: "الميزانية التقريبية بالدرهم (اختياري)",
        client_form_urgency: "مدى ضرورة أو استعجال الطلب *",
        client_form_desired_date: "تاريخ الإنجاز المطلوب",
        client_btn_publish_now: "نشر الطلب الآن",
        client_comp_title: "تقديم شكوى جديدة",
        client_comp_artisan: "اختر الحرفي الذي تعاملت معه *",
        client_comp_type: "نوع المخالفة *",
        client_comp_date: "تاريخ الواقعة *",
        client_comp_damage: "مبلغ الخسارة التقديري بالدرهم (اختياري)",
        client_comp_desc: "تاريخ وتفاصيل المشكلة بالكامل *",
        client_comp_evidence: "أرفق أدلة مادية أو صور فوتوغرافية أو مستندات",
        client_btn_submit_comp: "إرسال الشكوى رسمياً",
        client_comp_header_prev: "الشكاوى السابقة",
        client_profile_title: "تعديل المعلومات الشخصية",
        client_profile_avatar_btn: "تحديث الصورة",
        client_profile_name: "الاسم الكامل",
        client_profile_email: "البريد الإلكتروني",
        client_profile_phone: "تغيير رقم الهاتف",
        client_profile_city: "المدينة",
        client_profile_save: "حفظ التعديلات",
        // Artisan Dashboard
        artisan_header_title: "لوحة تحكم الحرفي",
        artisan_header_desc: "تحكم في بروفايلك وأضف أو احذف الأوراش ديالك بسهولة.",
        artisan_code_prefix: "رقم الحرفي: ",
        artisan_nav_overview: "نظرة عامة",
        artisan_nav_projects: "إدارة الأوراش",
        artisan_nav_jobs: "طلبات العمل المتاحة",
        artisan_nav_proposals: "عروضي المقترحة",
        artisan_nav_profile: "الملف الشخصي",
        artisan_nav_logout: "تسجيل الخروج",
        artisan_sec_overview: "نظرة سريعة",
        artisan_stat_total: "مجموع الأوراش",
        artisan_stat_images: "صور الأعمال",
        artisan_stat_videos: "فيديوهات الأعمال",
        artisan_stat_views: "إجمالي المشاهدات",
        artisan_project_title: "عنوان الورش",
        artisan_project_media: "نوع الوسيط",
        artisan_project_image: "صورة",
        artisan_project_video: "فيديو",
        artisan_project_location: "المكان",
        artisan_project_workdate: "تاريخ الإنجاز",
        artisan_project_path: "رابط/مسار الصورة أو الفيديو",
        artisan_project_file: "أو ارفع ملف (صورة/فيديو) من حاسوبك",
        artisan_project_desc: "وصف الورش",
        artisan_btn_add_project: "إضافة ورش جديد",
        artisan_btn_delete_project: "حذف الورش",
        artisan_profile_whatsapp: "WhatsApp",
        artisan_profile_address: "العنوان",
        artisan_profile_specialization: "التخصص",
        artisan_profile_experience: "سنوات الخبرة",
        artisan_profile_hours: "أوقات العمل",
        artisan_profile_avatar: "الصورة الشخصية (من جهازك)",
        artisan_profile_avatar_manual: "إدخال رابط/مسار الصورة يدويا (اختياري)",
        artisan_profile_avatar_remove: "حذف الصورة الحالية",
        artisan_profile_bio: "نبذة تعريفية",
        artisan_profile_add_sec: "إضافة ورش جديد من نفس الصفحة",
        artisan_profile_add_btn: "إضافة الورش",
        artisan_profile_delete_sec: "حذف الأوراش بسهولة",
        artisan_pending_alert: "حسابك حالياً قيد المراجعة من طرف الإدارة. يمكنك إضافة صور أعمالك وتحديث ملفك، لكنه لن يظهر للعملاء حتى يتم قبوله.",
        artisan_empty_portfolio: "مازال ما ضفتي حتى ورش. دخل لقسم إدارة الأوراش وزيد أول مشروع.",
        artisan_empty_delete: "ما كاين حتى ورش حاليا للحذف.",
        confirm_delete_project: "هل أنت متأكد من رغبتك في حذف هذا الورش؟",
        // Client Auth Pages
        cl_title: "دخول العملاء — حرفي",
        cl_portal: "بوابة العملاء — بوابتك لإنجاز جميع خدماتك",
        cl_brand: "حرفي",
        cl_welcome: "مرحباً بعودتك 👋",
        cl_sub: "سجّل دخولك للوصول إلى لوحة التحكم ونشر طلباتك للصناع",
        cl_email: "البريد الإلكتروني",
        cl_email_ph: "example@email.com",
        cl_pass: "كلمة المرور",
        cl_pass_ph: "••••••••",
        cl_remember: "تذكّرني",
        cl_forgot: "نسيت كلمة المرور؟",
        cl_btn: "تسجيل الدخول",
        cl_or_new: "أو إذا كنت جديداً",
        cl_no_account: "ليس لديك حساب؟",
        cl_create_free: "إنشاء حساب مجاني",
        cl_artisan_link: "أنت مقدم خدمات (حرفي)؟ سجّل دخولك من هنا",
        cr_title: "إنشاء حساب عميل — حرفي",
        cr_brand: "العميل",
        cr_portal: "انضم إلى آلاف العملاء الذين يثقون بـ حرفي",
        cr_welcome: "إنشاء حساب مجاني",
        cr_sub: "أنشئ حسابك وابدأ بنشر طلباتك وإيجاد أفضل الصناع المهرة",
        cr_name: "الاسم الكامل *",
        cr_name_ph: "مثال: يوسف العلوي",
        cr_email: "البريد الإلكتروني *",
        cr_phone: "رقم الهاتف النشط *",
        cr_city: "المدينة",
        cr_city_ph: "أدخل اسم المدينة يدوياً",
        cr_pass: "كلمة المرور *",
        cr_conf_pass: "تأكيد كلمة المرور *",
        cr_terms: "قرأت وأوافق على",
        cr_terms_use: "شروط الاستخدام",
        cr_terms_privacy: "سياسة الخصوصية",
        cr_terms_end: "الخاصة بمنصة حرفي.",
        cr_btn: "إنشاء حساب جديد",
        cr_have_account: "لديك حساب بالفعل؟",
        cr_login: "تسجيل الدخول",
        cr_artisan_link: "أنت مقدم خدمات (حرفي)؟ سجّل هنا",
        // Client Workspace
        cw_espace_client: "فضاء العميل",
        cw_welcome: "مرحباً، ",
        cw_dashboard: "لوحة التحكم الخاصة بي",
        cw_logout: "تسجيل الخروج",
        cw_title: "نشر مشروع جديد",
        cw_desc: "املأ التفاصيل أدناه لتلقي عروض من أفضل الحرفيين المؤهلين.",
        cw_proj_title: "عنوان المشروع",
        cw_proj_title_ph: "مثال: تجديد كامل للحمام",
        cw_category: "الفئة",
        cw_cat_select: "اختر فئة",
        cw_cat_carpentry: "نجارة",
        cw_cat_plumb: "سباكة",
        cw_cat_elec: "كهرباء",
        cw_cat_build: "بناء",
        cw_cat_paint: "صباغة",
        cw_cat_other: "أخرى...",
        cw_budget: "الميزانية المقدرة (درهم)",
        cw_optional: "(اختياري)",
        cw_budget_ph: "مثال: 5000",
        cw_detail_desc: "وصف مفصل",
        cw_detail_desc_ph: "صف حاجتك بالتفصيل...",
        cw_city: "المدينة",
        cw_city_ph: "مثال: الدار البيضاء",
        cw_neighborhood: "الحي",
        cw_neighborhood_ph: "مثال: المعاريف",
        cw_urgency: "الأهمية / الاستعجال",
        cw_urg_normal: "عادية",
        cw_urg_high: "عالية (في أقرب وقت ممكن)",
        cw_urg_urgent: "عاجلة (فوري)",
        cw_urg_low: "منخفضة (مجدولة لوقت لاحق)",
        cw_date: "التاريخ المطلوب",
        cw_btn_pub: "نشر المشروع",
        cw_publishing: "جاري النشر...",
        cw_pub_success: "تم نشر المشروع بنجاح! جاري التوجيه...",
        cw_pub_err: "خطأ أثناء النشر.",
        cw_srv_err: "خطأ في الخادم. يرجى المحاولة مرة أخرى.",
        // Artisan Marketplace
        am_title: "حرفي برو",
        am_welcome: "مرحباً، ",
        am_dashboard: "لوحة التحكم الخاصة بي",
        am_logout: "تسجيل الخروج",
        am_header_title: "سوق المشاريع",
        am_header_desc: "اعثر على فرص تتناسب مع مهاراتك عبر أنحاء المغرب.",
        am_smart_filters: "فلاتر ذكية",
        am_search_ph: "ابحث (مثال: كهرباء، الدار البيضاء)...",
        am_all_categories: "جميع الفئات",
        am_my_spec: "★ تخصصي",
        am_all_cities: "جميع المدن",
        am_my_city: "📍 مدينتي",
        am_empty_title: "لا يوجد أي مشروع متاح حالياً",
        am_empty_desc: "عُد لاحقاً أو قم بتعديل الفلاتر الخاصة بك.",
        am_budget_est: "الميزانية المتوقعة",
        am_to_discuss: "قابل للنقاش",
        am_mad: "درهم",
        am_location: "الموقع",
        am_client_id: "رقم العميل",
        am_verified: "مُوثق",
        am_proposals: "العروض",
        am_received: "مُستلمة",
        am_btn_details: "التفاصيل",
        am_btn_offer: "تقديم عرض",
        am_urg_medium: "عادية",
        am_urg_high: "عالية",
        am_urg_urgent: "عاجلة",
        am_urg_low: "منخفضة"
    },
    fr: {
        brand_name: "Hirafi.ma",
        brand_title: "Service des Artisans Marocains",
        brand_subtitle: "Plateforme de mise en relation client-artisan",
        nav_home: "Accueil",
        nav_search: "Rechercher",
        nav_register: "Inscription Artisan",
        nav_contact: "Contactez-nous",
        nav_login: "Connexion",
        nav_signup: "S'inscrire",
        hero_title: '<span class="text-primary">Les meilleurs artisans</span> marocains à votre service',
        hero_subtitle: "Plus de 2000 artisans professionnels partout au Maroc prêts à réaliser vos projets avec qualité et au meilleur tarif.",
        hero_btn_search: "Trouver un Artisan",
        hero_btn_register: "Devenir Pro",
        hero_btn_client_register: "S'inscrire comme Client",
        hero_badge: "Artisans certifiés et vérifiés",
        quick_search_title: "Trouver un artisan dans votre ville",
        quick_search_service_label: "Quel type de service recherchez-vous ?",
        quick_search_service_select: "Choisir le métier",
        quick_search_city_label: "Ville",
        quick_search_city_select: "Choisir la ville",
        quick_search_btn: "Rechercher",
        professions_title: "Parcourir nos métiers",
        professions_subtitle: "Sélectionnez le métier requis et contactez directement nos professionnels qualifiés",
        p_carpenter_title: "Menuiserie",
        p_carpenter_desc: "Conception, installation et réparation méticuleuse de meubles, portes, fenêtres et produits en bois.",
        p_plumber_title: "Plomberie",
        p_plumber_desc: "Résolution des fuites, évacuations d'eau, installation et maintenance des réseaux de plomberie.",
        p_electrician_title: "Électricité",
        p_electrician_desc: "Installation et dépannage électrique domestique, pose de luminaires en totale sécurité.",
        p_painter_title: "Peinture",
        p_painter_desc: "Réalisation de peintures modernes et peintures décoratives intérieures et extérieures de qualité.",
        p_mason_title: "Maçonnerie",
        p_mason_desc: "Rénovation, gros œuvre, enduits et travaux généraux de bâtiment avec précision.",
        p_blacksmith_title: "Métallurgie",
        p_blacksmith_desc: "Fabrication de portails, garde-corps, grilles de protection et toutes structures métalliques.",
        p_tailor_title: "Couture",
        p_tailor_desc: "Couture traditionnelle et moderne, confection sur mesure avec finitions impeccables.",
        p_mechanic_title: "Mécanique Auto",
        p_mechanic_desc: "Diagnostic et réparation de pannes de moteurs et d'électricité automobile par des professionnels.",
        stat_craftsmen: "Artisans inscrits",
        stat_cities: "Villes couvertes",
        stat_completed: "Projets réalisés",
        stat_rating: "Satisfaction Client",
        how_it_works_title: "Comment ça fonctionne",
        step_1_title: "1. Rechercher",
        step_1_desc: "Sélectionnez le métier et votre ville pour trouver les spécialistes à proximité de chez vous.",
        step_2_title: "2. Comparer les profils",
        step_2_desc: "Consultez les détails du profil, les photos des projets passés et les avis réels laissés par les clients.",
        step_3_title: "3. Contacter et démarrer",
        step_3_desc: "Entrez en contact par téléphone ou WhatsApp pour fixer les détails et démarrer vos travaux en confiance.",
        trust_section_title: "Pourquoi choisir notre plateforme ?",
        trust_1_title: "Sécurité & Fiabilité",
        trust_1_desc: "Nous vérifions l'identité des artisans inscrits afin de vous assurer la confiance.",
        trust_2_title: "Zéro Intermédiaire",
        trust_2_desc: "Contactez directement les artisans sans frais cachés ni de commissions supplémentaires.",
        trust_3_title: "Avis Réels certifiés",
        trust_3_desc: "Des évaluations transparentes de clients réels qui ont testé les prestations.",
        reviews_title: "Témoignages de nos clients",
        reviews_subtitle: "Des avis authentiques de particuliers satisfaits du travail des artisans dans différentes villes",
        footer_desc: "Plateforme leader de mise en relation directe avec les artisans professionnels à travers le Maroc depuis 2026.",
        footer_links_title: "Liens Rapides",
        footer_cities_title: "Villes principales",
        footer_newsletter_title: "Newsletter",
        footer_newsletter_desc: "Abonnez-vous pour recevoir les nouveautés et les conseils de nos experts.",
        footer_newsletter_placeholder: "Votre adresse e-mail",
        footer_newsletter_notice: "Nous respectons votre vie privée. Votre adresse ne sera jamais partagée.",
        copyright_text: "Tous droits réservés. Plateforme Hirafi.ma 2026.",
        search_hero_title: "Rechercher un Artisan",
        search_skill_filter: "Métier",
        search_skill_placeholder: "Sélectionner le métier",
        search_city_filter: "Ville",
        search_city_placeholder: "Toutes les villes",
        search_rating_filter: "Note minimale",
        search_rating_placeholder: "Toutes les notes",
        search_btn_text: "Rechercher",
        search_clear_filters: "Réinitialiser",
        search_loading: "Chargement des résultats...",
        search_no_results: "Aucun artisan ne correspond à vos critères de recherche.",
        search_experience: "ans d'expérience",
        search_view_profile: "Voir le Profil",
        search_contact_phone: "Appeler",
        search_verified: "Vérifié",
        search_featured: "Vedette",
        profile_back_to_search: "Retour aux résultats",
        profile_skills_title: "Compétences & Expériences",
        profile_portfolio_title: "Galerie de Réalisations",
        profile_contact_title: "Informations de Contact Direct",
        profile_reviews_title: "Avis Clients",
        profile_no_reviews: "Aucun avis client pour le moment.",
        login_title: "Connexion Artisan",
        login_subtitle: "Connectez-vous pour accéder à votre tableau de bord",
        login_email_label: "Adresse e-mail",
        login_email_placeholder: "example@email.com",
        login_code_label: "Code artisan",
        login_code_placeholder: "CRAFT261549",
        login_code_hint: "Entrez votre e-mail ou votre code artisan",
        login_password_label: "Mot de passe",
        login_password_placeholder: "••••••••",
        login_or: "ou",
        login_error_missing: "Veuillez entrer votre e-mail ou votre code artisan",
        login_error_password: "Veuillez entrer votre mot de passe",
        login_success: "Connexion réussie ✅",
        login_error_invalid: "Identifiants incorrects",
        login_error_network: "Erreur de connexion. Veuillez réessayer.",
        login_identifier_label: "Email ou code artisan",
        login_identifier_placeholder: "example@email.com ou CRAFT261549",
        login_password_label: "Mot de passe",
        login_password_placeholder: "Entrez votre mot de passe",
        login_remember: "Se souvenir de moi",
        login_forgot: "Mot de passe oublié ?",
        login_btn: "Connexion",
        login_gmail: "Se connecter avec Gmail",
        login_gmail_soon: "L'authentification Gmail sera bientôt disponible",
        login_no_account: "Pas encore de compte ?",
        login_signup_link: "Inscrivez-vous ici",
        login_welcome: "Bienvenue",
        register_title: "Inscription Nouvel Artisan",
        register_subtitle: "Remplissez le formulaire pour créer votre compte professionnel",
        register_info_title: "Inscription simple et sécurisée",
        register_info_desc: "Rejoignez le réseau des artisans professionnels. Créez votre profil, présentez vos compétences et augmentez vos chances de décrocher des missions.",
        register_step1: "Données personnelles",
        register_step2: "Métier",
        register_step3: "Photos & Révision",
        register_nav_home: "Accueil",
        register_nav_login: "Connexion Artisan",
        contact_title: "Contacter l'Administration",
        contact_subtitle: "Remplissez vos informations et envoyez votre demande. L'administration vous répondra rapidement.",
        contact_name: "Nom complet",
        contact_type: "Vous êtes",
        contact_type_guest: "Visiteur",
        contact_type_craftsman: "Artisan",
        contact_type_client: "Client",
        contact_phone: "Numéro de téléphone",
        contact_subject: "Sujet (optionnel)",
        contact_message: "Message",
        contact_message_placeholder: "Écrivez votre question ou demande ici...",
        contact_send_btn: "Envoyer le message",
        contact_back: "Retour à l'accueil",
        contact_admin_chat: "Chat Administration (inscrits uniquement)",
        contact_about_title: "Qui sommes-nous ?",
        contact_about_text: "La plateforme Hirafi.ma connecte les artisans marocains avec des visiteurs à la recherche de services fiables. Notre objectif est d'organiser la communication et de mettre en valeur les artisans professionnels.",
        contact_confirm_login: "Vous devez vous connecter pour contacter l'administration. Souhaitez-vous aller à la page de connexion ?",
        contact_send_success: "Message envoyé avec succès",
        contact_send_error: "Échec de l'envoi du message",
        contact_conn_error: "Un problème de connexion est survenu, veuillez réessayer.",
        admin_login_title: "🔐 Connexion Administration",
        admin_login_badge_title: "🔒 Zone Sécurisée",
        admin_login_badge_desc: "Accès sécurisé exclusif pour l'administrateur",
        admin_login_email: "Email",
        admin_login_password: "Mot de passe",
        admin_login_remember: "Se souvenir de moi sur cet appareil",
        admin_login_btn: "Connexion sécurisée",
        admin_dashboard_title: "Tableau de Bord",
        admin_brand_title: "Tableau de Bord",
        admin_feat1_title: "Gestion des artisans",
        admin_feat1_desc: "Ajouter, modifier ou supprimer des artisans",
        forgot_title: "Mot de passe oublié",
        forgot_desc: "Entrez votre e-mail pour recevoir le lien de réinitialisation.",
        forgot_btn: "Envoyer le lien",
        forgot_back: "← Retour à la connexion",
        nav_blog: "Blog",
        nav_faq: "FAQ",
        nav_cities: "Villes",
        cities_hero_title: "Principales villes, diverses spécialités, recherche simplifiée.",
        cities_discover: "Découvrir la ville",
        faq_hero_title: "Réponses claires et rapides",
        blog_hero_title: "Le blog qui vous aide à prendre des décisions en toute confiance.",
        idx_prof_carpentry: "Menuiserie",
        idx_prof_plumbing: "Plomberie",
        idx_prof_electricity: "Électricité",
        idx_prof_building: "Construction",
        idx_prof_painting: "Peinture",
        idx_prof_blacksmith: "Métallurgie",
        idx_prof_tailoring: "Couture",
        idx_prof_design: "Design",
        idx_prof_photography: "Photographie",
        idx_prof_cooking: "Cuisine",
        idx_prof_farming: "Agriculture",
        idx_prof_events: "Événementiel",
        idx_prof_mechanic: "Mécanique",
        idx_prof_other: "Autres métiers",
        idx_regions_major: "Grandes Régions",
        idx_regions_other: "Autres Villes",
        idx_city_casablanca: "Casablanca",
        idx_city_rabat: "Rabat",
        idx_city_fes: "Fès",
        idx_city_marrakech: "Marrakech",
        idx_city_chichaoua: "Chichaoua",
        idx_city_tangier: "Tanger",
        idx_city_meknes: "Meknès",
        idx_city_agadir: "Agadir",
        idx_city_tetouan: "Tétouan",
        idx_city_oujda: "Oujda",
        idx_city_kenitra: "Kénitra",
        idx_city_mohammedia: "Mohammédia",
        idx_city_beni_mellal: "Béni Mellal",
        idx_city_safi: "Safi",
        idx_city_eljadida: "El Jadida",
        idx_city_taza: "Taza",
        idx_city_larache: "Larache",
        idx_city_khouribga: "Khouribga",
        idx_city_temara: "Témara",
        idx_city_sale: "Salé",
        idx_city_benguerir: "Ben Guerir",
        idx_city_ouarzazate: "Ouarzazate",
        idx_city_dakhla: "Dakhla",
        idx_city_laayoune: "Laâyoune",
        idx_popular_jobs_title: "Métiers populaires :",
        idx_job_carpenter: "Menuisier",
        idx_job_plumber: "Plombier",
        idx_job_electrician: "Électricien",
        idx_job_painter: "Peintre",
        idx_job_builder: "Maçon",
        idx_job_mechanic: "Mécanicien",
        idx_prof_card1_title: "Menuiserie et Meubles",
        idx_prof_card1_desc: "Conception, fabrication et installation de meubles",
        idx_prof_card1_stat1: "320+ Artisans",
        idx_prof_card1_link: "Parcourir les menuisiers",
        idx_prof_card2_title: "Plomberie et Sanitaire",
        idx_prof_card2_desc: "Installation et réparation de plomberie",
        idx_prof_card2_stat1: "280+ Artisans",
        idx_prof_card2_link: "Parcourir les plombiers",
        idx_prof_card3_title: "Électricité Domestique",
        idx_prof_card3_desc: "Installation et réparation des circuits électriques",
        idx_prof_card3_stat1: "350+ Artisans",
        idx_prof_card3_link: "Parcourir les électriciens",
        idx_prof_card4_title: "Construction et Bâtiment",
        idx_prof_card4_desc: "Construction et rénovation de maisons",
        idx_prof_card4_stat1: "420+ Artisans",
        idx_prof_card4_link: "Parcourir les maçons",
        idx_step_subtitle: "3 étapes simples pour un service exceptionnel",
        idx_featured_title: "Artisans Vedettes",
        idx_featured_subtitle: "Découvrez les meilleurs artisans très bien notés sur notre plateforme",
        idx_feat_badge_req: "Le plus demandé",
        idx_feat_badge_fast: "Réponse la plus rapide",
        idx_feat_badge_top: "Le mieux noté",
        idx_feat_badge_exp: "Expert Certifié",
        idx_feat_prof_carp: "Menuisier Professionnel",
        idx_feat_prof_elec: "Électricien Domestique",
        idx_feat_prof_plumb: "Plombier Professionnel",
        idx_feat_prof_build: "Constructeur",
        idx_feat_review_1: "(128 avis)",
        idx_feat_review_2: "(94 avis)",
        idx_feat_review_3: "(76 avis)",
        idx_feat_review_4: "(203 avis)",
        idx_feat_exp_12: "Expérience: 12 ans",
        idx_feat_exp_8: "Expérience: 8 ans",
        idx_feat_exp_15: "Expérience: 15 ans",
        idx_feat_exp_20: "Expérience: 20 ans",
        idx_feat_btn_view: "Voir le Profil",
        idx_cta_title: "Êtes-vous un artisan professionnel ?",
        idx_cta_text: "Rejoignez notre plateforme et augmentez vos opportunités avec des milliers de clients",
        idx_cta_feat1: "Accès à des milliers de nouveaux clients",
        idx_cta_feat2: "Profil professionnel avec galerie",
        idx_cta_feat3: "Des notes et avis qui renforcent votre crédibilité",
        idx_cta_feat4: "Gestion facile des demandes et conversations",
        idx_cta_btn1: "S'inscrire comme Pro",
        idx_cta_btn2: "Comment ça marche ?",
        idx_trust_sub: "Une plateforme de confiance avec des milliers d'artisans certifiés",
        idx_trust_t1: "Artisans Certifiés",
        idx_trust_d1: "Tous les artisans subissent une vérification d'identité avant de rejoindre",
        idx_trust_t2: "Paiement Sécurisé",
        idx_trust_d2: "Système de paiement garanti et sûr. Nous offrons un environnement fiable",
        idx_trust_t3: "Support 24/7",
        idx_trust_d3: "Une équipe de support disponible en permanence pour vous aider",
        idx_trust_t4: "Garantie de Remboursement",
        idx_trust_d4: "Garantie de remboursement sous 48h si vous n'êtes pas satisfait",
        idx_rev_sub: "Ce que disent nos clients de leur expérience",
        idx_rev_t1: "\"J'ai trouvé un excellent menuisier à Casablanca, très bon traitement.\"",
        idx_rev_t2: "\"L'électricien était très professionnel et a terminé à temps avec un prix raisonnable.\"",
        idx_rev_t3: "\"Livraison rapide et facile, le plombier était très respectueux.\"",
        idx_stat_title: "Statistiques de Réussite",
        idx_stat_sub: "De nos chiffres, votre succès est notre fierté",
        idx_footer_terms: "Conditions d'utilisation",
        idx_footer_privacy: "Politique de confidentialité",
        idx_footer_cookies: "Politique des cookies",
        // Artisan Showcase Carousel
        showcase_eyebrow: "Artisans certifiés et de confiance",
        showcase_title_1: "Découvrez les meilleurs artisans",
        showcase_title_2: "et leurs réalisations",
        showcase_subtitle: "Des exemples concrets des travaux d'artisans professionnels dans diverses spécialités — Qualité exceptionnelle et expertise reconnue",
        showcase_btn_view: "Voir le profil",
        prof_carpenter: "Menuiserie",
        prof_plumber: "Plomberie",
        prof_electrician: "Électricité",
        prof_painter: "Peinture",
        prof_welder: "Ferronnerie",
        prof_tailor: "Couture",
        prof_decorator: "Décoration",
        prof_traditional: "Artisanat Traditionnel",
        showcase_serv_carpenter: "Conception et fabrication de meubles modernes et traditionnels",
        showcase_serv_plumber: "Réparation et installation de systèmes de plomberie",
        showcase_serv_electrician: "Installation et maintenance des réseaux électriques",
        showcase_serv_painter: "Peinture et décoration murale en techniques modernes",
        showcase_serv_welder: "Fabrication de portes et fenêtres en fer forgé marocain",
        showcase_serv_tailor: "Confection de djellabas et kaftan de style marocain authentique",
        showcase_serv_decorator: "Design d'intérieur de style marocain contemporain",
        showcase_serv_traditional: "Zellige, stuc et artisanat traditionnel marocain authentique",
        // Gallery Section
        gallery_plumber_title: "Plomberie professionnelle",
        gallery_plumber_desc: "Réparation rapide et précise de tous les systèmes d'eau",
        gallery_electrician_title: "Électricité domestique",
        gallery_electrician_desc: "Installation et maintenance de circuits électriques sécurisés",
        gallery_carpenter_title: "Menuiserie haut de gamme",
        gallery_carpenter_desc: "Conception de meubles en bois selon les normes les plus strictes",
        gallery_painter_title: "Peinture professionnelle",
        gallery_painter_desc: "Finitions de couleurs élégantes pour des murs stylés",
        gallery_welder_title: "Soudure précise",
        gallery_welder_desc: "Assemblages métalliques robustes et qualité supérieure",
        // Digital Platform Section
        digital_platform_badge: "Plateforme numérique pour artisans",
        digital_platform_title: "Découvrez une plateforme artisanale d'envergure mondiale",
        digital_platform_subtitle: "Recherche intelligente, évaluations réelles, réservations sécurisées et support local ; le tout dans une interface propre et rapide, digne des plus grandes plateformes mondiales.",
        digital_platform_search_title: "Recherche intelligente et rapide",
        digital_platform_search_desc: "Utilisez le filtrage par ville et métier pour afficher les résultats les plus précis rapidement.",
        digital_platform_profiles_title: "Profils vérifiés",
        digital_platform_profiles_desc: "Artisans avec évaluations, photos claires et informations complètes garantissant un choix en toute confiance.",
        digital_platform_booking_title: "Réservation sécurisée et facile",
        digital_platform_booking_desc: "Planifiez le service et communiquez avec l'artisan de manière claire et flexible.",
        digital_platform_support_title: "Support local direct",
        digital_platform_support_desc: "Notre équipe est prête à répondre à vos questions et vous guider vers le meilleur service.",
        digital_platform_btn: "Commencez votre recherche maintenant",
        brand_short_title: "Hirafi.ma",
        trust_subtitle: "Une plateforme de confiance avec des milliers d'artisans vérifiés à travers tout le Royaume du Maroc",
        loading_text: "Vérification des données en cours...",
        manual_skill_placeholder: "Ou saisissez le métier manuellement",
        manual_city_placeholder: "Ou saisissez la ville manuellement",
        load_more: "Afficher plus",
        no_results: "Aucun résultat trouvé",
        copyright_ar: "Tous droits réservés. Plateforme Hirafi.ma 2026.",
        login_brand: "Hirafi",
        login_brand_subtitle: "Plateforme des artisans",
        login_nav_signup: "S'inscrire",
        login_info_title: "Bienvenue",
        login_benefit1: "Protection de vos données et de votre vie privée",
        login_benefit2: "Interface facile à utiliser",
        login_benefit3: "Présentation de votre portfolio et de vos certificats",
        login_benefit4: "Rejoignez la communauté des artisans marocains",
        login_benefit5: "Augmentez vos chances d'obtenir des clients",
        profile_not_found: "Artisan non trouvé",
        profile_not_found_desc: "Désolé, cet artisan n'a pas été trouvé",
        profile_btn_search: "Rechercher un artisan",
        profile_contact_now: "Contacter maintenant",
        profile_whatsapp: "WhatsApp",
        profile_no_portfolio: "Aucune réalisation disponible pour le moment",
        profile_loading: "Chargement du profil en cours...",
        profile_section_desc: "Description",
        profile_section_bio: "À propos de l'artisan",
        profile_section_skills: "Compétences",
        profile_section_portfolio: "Réalisations précédentes",
        profile_section_contact: "Informations de contact",
        profile_section_admin_chat: "Messagerie de l'administration",
        profile_admin_chat_desc: "Si vous êtes artisan et avez besoin de contacter l'administration, utilisez le chat local pour envoyer votre message et suivre les réponses.",
        profile_admin_chat_btn: "Ouvrir le chat administration",
        search_results_summary: "Affichage de ${count} sur ${total} artisans",
        cities_brand_text: "Hirafi.ma",
        cities_hero_subtitle: "De Casablanca à Agadir, la plateforme met en valeur les artisans les plus proches selon votre ville et votre spécialité.",
        cities_section_title: "Aperçu rapide des villes",
        cities_section_desc: "Chaque carte vous donne un aperçu de la demande et des spécialités les plus présentes, puis vous pouvez passer directement à la recherche filtrée.",
        cities_detail_title: "Détails de chaque ville",
        cities_detail_desc: "Un contenu concis vous donne une impression pratique des spécialités demandées, de la nature des clients et de la meilleure façon de commencer votre recherche dans chaque ville.",
        cities_footer_text: "© 2026 Hirafi.ma - Couverture locale avec un style premium.",
        blog_brand_text: "Hirafi.ma",
        blog_hero_subtitle: "Ici, nous partageons des conseils pratiques, de vraies histoires de succès et des orientations intelligentes qui intéressent clients et artisans. L'objectif est de rendre l'expérience Hirafi.ma plus claire, plus élégante et plus professionnelle, de la première visite jusqu'à la fin du projet.",
        blog_featured_meta: "Article vedette | 6 min de lecture",
        blog_featured_title: "Comment choisir un artisan professionnel sans perdre de temps ni de budget ?",
        blog_featured_desc: "Nous y expliquons les critères à vérifier avant tout contact : qualité du profil, clarté des travaux précédents, rapidité de réponse, et les questions à poser avant de démarrer le service.",
        blog_hl1: "Comment distinguer un profil ordinaire d'un profil professionnel",
        blog_hl2: "Indicateurs qui montrent le sérieux avant l'accord",
        blog_hl3: "Méthode rapide pour évaluer le rapport prix-qualité",
        blog_section_title: "Articles récents",
        blog_section_desc: "Contenu organisé sous forme de sujets pratiques et faciles à appliquer, que vous soyez un client à la recherche d'un service de qualité ou un artisan souhaitant développer sa présence numérique.",
        blog_newsletter_title: "Vous voulez rester informé des derniers conseils et opportunités ?",
        blog_newsletter_desc: "Laissez-nous votre email et recevez des actualités concises et utiles sur les meilleures façons de travailler avec les artisans, d'améliorer votre profil et d'utiliser la plateforme de manière plus intelligente.",
        blog_newsletter_placeholder: "Votre adresse e-mail",
        blog_newsletter_btn: "S'abonner maintenant",
        blog_insight1_title: "Vision claire",
        blog_insight1_desc: "Notre contenu n'est pas général. Chaque article est écrit pour servir une décision réelle dans l'expérience de réservation ou de prestation de service.",
        blog_insight2_title: "Qualité supérieure",
        blog_insight2_desc: "Nous nous concentrons sur la qualité, la confiance et l'organisation plutôt que sur les discours généraux. L'objectif est une expérience réellement premium.",
        blog_insight3_title: "Étapes applicables",
        blog_insight3_desc: "Chaque idée vous donne une étape claire : que demander, que préparer et combien comparer avant l'accord.",
        blog_footer_text: "© 2026 Hirafi.ma - Contenu au service de la confiance et de la qualité.",
        faq_brand_text: "Hirafi.ma",
        faq_hero_subtitle: "Toutes les questions que se posent clients et artisans trouvent une réponse organisée et professionnelle. Nous avons rassemblé les questions les plus fréquentes sur la recherche, l'inscription, la tarification, la confiance et la messagerie.",
        faq_support_title: "Vous n'avez pas trouvé la réponse qui vous convient ?",
        faq_support_desc: "Si vous avez une question spécifique ou souhaitez un guide direct pour un cas particulier, l'administration de la plateforme peut vous accompagner via la page de contact ou le centre de messagerie.",
        faq_support_btn1: "Contacter l'administration",
        faq_support_btn2: "Essayez la recherche maintenant",
        faq_footer_text: "© 2026 Hirafi.ma - Réponses claires et parcours plus professionnel.",
        admin_feat2_title: "Gestion des points",
        admin_feat2_desc: "Saisie des points et rapports académiques",
        admin_feat3_title: "Gestion des leçons",
        admin_feat3_desc: "Ajout et suivi des leçons et conférences",
        admin_feat4_title: "Rapports et statistiques",
        admin_feat4_desc: "Affichage de rapports détaillés et de statistiques complètes",
        contact_email_label: "Email",
        contact_email_placeholder: "exemple@gmail.com",
        forgot_email_placeholder: "exemple@email.com",
        admin_login_email_placeholder: "admin@hirafi.ma",
        footer_home: "Accueil",
        footer_search: "Rechercher un artisan",
        footer_register: "S'inscrire en tant qu'artisan",
        footer_contact: "Contact",
        footer_blog: "Blog",
        footer_faq: "FAQ",
        footer_contact_address: "Marrakech, Maroc",
        showcase_review_label: "avis",
        showcase_serv_tailor_2: "Confection et design de vêtements professionnels confortables et élégants",
        showcase_serv_decorator_2: "Aménagement et rénovation d'espaces domestiques élégants et confortables",
        showcase_serv_tailor_3: "Confection de vêtements professionnels et abayas avec broderies élégantes",
        showcase_serv_electrician_2: "Inspection et installation de tableaux électriques sécurisés et éclairés",
        showcase_serv_carpenter_2: "Conception de mobilier sur mesure et restauration d'objets en bois avec finitions précises",
        footer_logo_text: "Hirafi.ma",
        mp_btn_artisan: "Je suis Artisan",
        mp_btn_artisan_sub: "Trouver des projets disponibles",
        mp_btn_client: "Je suis Client",
        mp_btn_client_sub: "Publier un Projet",
        mp_artisan_card_title: "Espace Artisan",
        mp_artisan_card_sub: "Trouvez des projets disponibles et proposez vos services.",
        mp_client_card_title: "Espace Client",
        mp_client_card_sub: "Publiez un nouveau projet et trouvez l'artisan idéal.",
        mp_btn_creer_compte: "Créer un compte",
        mp_btn_deja_artisan: "Déjà Artisan",
        mp_btn_deja_client: "Déjà Client",
        mp_eyebrow: "Nouvelles Opportunités",
        mp_title: "Dernières Demandes Clients",
        mp_subtitle: "Découvrez les derniers projets publiés par les clients et soumettez votre proposition pour gagner de nouvelles opportunités.",
        modal_artisan_space: "Espace Artisan",
        modal_artisan_login_tab: "Je suis déjà Artisan",
        modal_create_account: "Créer un compte",
        modal_email: "Email",
        modal_password: "Mot de passe",
        modal_login_btn: "Se connecter",
        modal_fullname: "Nom Complet",
        modal_phone: "Numéro de Téléphone",
        modal_profession: "Profession",
        modal_city: "Ville",
        modal_confirm_pass: "Confirmer le mot de passe",
        modal_terms: "J'accepte les conditions d'utilisation",
        modal_register_btn: "Créer mon compte",
        modal_client_space: "Espace Client",
        modal_client_login_tab: "Je suis déjà Client",
        // Client Dashboard & Workspace
        client_nav_requests: "Mes Demandes",
        client_nav_publish: "Publier un Projet",
        client_nav_complaints: "Centre des Réclamations",
        client_nav_profile: "Modifier le Profil",
        client_nav_logout: "Se Déconnecter",
        client_header_requests: "Mes Demandes de Travail",
        client_header_publish: "Publier un nouveau Projet",
        client_header_complaints: "Centre des Plaintes & Violations",
        client_header_profile: "Modifier le Profil et Profil Personnel",
        client_stat_total: "Total des projets",
        client_stat_waiting: "En attente d'offres",
        client_stat_inprogress: "En cours d'exécution",
        client_stat_offers: "Total des offres reçues",
        client_sec_published: "Demandes de Travail Publiées",
        client_loading_requests: "Chargement de vos demandes...",
        client_sec_proposals: "Offres de Prix Proposées",
        client_btn_back: "Retour",
        client_tag_waiting: "En attente",
        client_btn_proposals: "Offres",
        client_proposal_specialty: "Spécialité : ",
        client_proposal_city: "Ville : ",
        client_proposal_rating: "Évaluation : ",
        client_proposal_trust: "Fiabilité : ",
        client_proposal_exp: "Expérience : ",
        client_proposal_years: "ans",
        client_proposal_duration: "Durée : ",
        client_status_accepted: "Accepté",
        client_btn_accept: "Accepter & Contacter",
        client_form_title: "Titre du projet / Service *",
        client_form_category: "Type de service / Catégorie *",
        client_form_preference: "Préférence de contact *",
        client_form_description: "Description détaillée du travail *",
        client_btn_next: "Suivant",
        client_btn_prev: "Précédent",
        client_form_media_lbl: "Joindre des photos/vidéos claires du travail ou problème",
        client_form_media_drag: "Glissez les fichiers ici ou cliquez pour choisir",
        client_form_media_hint: "Vous pouvez choisir plusieurs images ou vidéos (JPG, PNG, WEBP, MP4)",
        client_form_city: "Ville *",
        client_form_neighborhood: "Quartier ou région",
        client_form_gps: "Joindre la position géographique (GPS)",
        client_form_gps_btn: "Déterminer ma position actuelle",
        client_form_gps_status: "Coordonnées de position non définies",
        client_form_budget: "Budget estimé en MAD (Optionnel)",
        client_form_urgency: "Urgence de la demande *",
        client_form_desired_date: "Date de réalisation souhaitée",
        client_btn_publish_now: "Publier le projet maintenant",
        client_comp_title: "Soumettre une nouvelle plainte",
        client_comp_artisan: "Choisir l'artisan concerné *",
        client_comp_type: "Type de violation *",
        client_comp_date: "Date de l'incident *",
        client_comp_damage: "Dommage estimé en MAD (Optionnel)",
        client_comp_desc: "Détails complets du problème *",
        client_comp_evidence: "Joindre des photos, documents ou preuves physiques",
        client_btn_submit_comp: "Envoyer la plainte officiellement",
        client_comp_header_prev: "Historique des réclamations",
        client_profile_title: "Modifier les Informations Personnelles",
        client_profile_avatar_btn: "Mettre à jour la photo",
        client_profile_name: "Nom Complet",
        client_profile_email: "Adresse Email",
        client_profile_phone: "Changer de téléphone",
        client_profile_city: "Ville",
        client_profile_save: "Confirmer les modifications",
        // Artisan Dashboard
        artisan_header_title: "Tableau de Bord de l'Artisan",
        artisan_header_desc: "Gérez vos informations de profil, chantiers et offres en toute simplicité.",
        artisan_code_prefix: "Code Artisan : ",
        artisan_nav_overview: "Aperçu",
        artisan_nav_projects: "Gérer mes Chantiers",
        artisan_nav_jobs: "Demandes Disponibles",
        artisan_nav_proposals: "Mes Offres",
        artisan_nav_profile: "Profil Personnel",
        artisan_nav_logout: "Se Déconnecter",
        artisan_sec_overview: "Aperçu Rapide",
        artisan_stat_total: "Total chantiers",
        artisan_stat_images: "Photos de chantiers",
        artisan_stat_videos: "Vidéos de réalisations",
        artisan_stat_views: "Total des vues",
        artisan_project_title: "Titre du chantier",
        artisan_project_media: "Type de média",
        artisan_project_image: "Image",
        artisan_project_video: "Vidéo",
        artisan_project_location: "Lieu",
        artisan_project_workdate: "Date de réalisation",
        artisan_project_path: "Chemin/Lien de l'image ou vidéo",
        artisan_project_file: "Ou téléverser un fichier (Photo/Vidéo) depuis l'ordinateur",
        artisan_project_desc: "Description du chantier",
        artisan_btn_add_project: "Ajouter un chantier",
        artisan_btn_delete_project: "Supprimer le projet",
        artisan_profile_whatsapp: "WhatsApp",
        artisan_profile_address: "Adresse",
        artisan_profile_specialization: "Spécialité",
        artisan_profile_experience: "Années d'expérience",
        artisan_profile_hours: "Heures de travail",
        artisan_profile_avatar: "Photo de Profil (De votre appareil)",
        artisan_profile_avatar_manual: "Entrer le lien de la photo manuellement (Optionnel)",
        artisan_profile_avatar_remove: "Supprimer la photo actuelle",
        artisan_profile_bio: "À propos / Bio",
        artisan_profile_add_sec: "Ajouter un chantier depuis cette page",
        artisan_profile_add_btn: "Ajouter le chantier",
        artisan_profile_delete_sec: "Supprimer des chantiers facilement",
        artisan_pending_alert: "Votre compte est actuellement en cours de révision par l'administration. Vous pouvez ajouter des photos de vos réalisations et mettre à jour votre profil, mais il ne sera pas visible par les clients tant qu'il n'aura pas été validé.",
        artisan_empty_portfolio: "Vous n'avez pas encore ajouté de chantier. Allez dans la section de gestion des chantiers pour ajouter votre premier projet.",
        artisan_empty_delete: "Aucun chantier disponible pour la suppression.",
        confirm_delete_project: "Êtes-vous sûr de vouloir supprimer ce projet ?",
        // Client Auth Pages
        cl_title: "Connexion Client — Hirafi",
        cl_portal: "Portail Client — Votre portail pour tous vos services",
        cl_brand: "Hirafi",
        cl_welcome: "Bon retour 👋",
        cl_sub: "Connectez-vous pour accéder à votre tableau de bord et publier vos demandes",
        cl_email: "Courriel",
        cl_email_ph: "exemple@email.com",
        cl_pass: "Mot de passe",
        cl_pass_ph: "••••••••",
        cl_remember: "Se souvenir de moi",
        cl_forgot: "Mot de passe oublié ?",
        cl_btn: "Se connecter",
        cl_or_new: "Ou si vous êtes nouveau",
        cl_no_account: "Vous n'avez pas de compte ?",
        cl_create_free: "Créer un compte gratuit",
        cl_artisan_link: "Vous êtes artisan ? Connectez-vous ici",
        cr_title: "Créer un compte client — Hirafi",
        cr_brand: "Client",
        cr_portal: "Rejoignez des milliers de clients qui font confiance à Hirafi",
        cr_welcome: "Créer un compte gratuit",
        cr_sub: "Créez votre compte et commencez à publier vos demandes pour trouver les meilleurs artisans",
        cr_name: "Nom complet *",
        cr_name_ph: "Ex: Youssef Alaoui",
        cr_email: "Courriel *",
        cr_phone: "Numéro de téléphone actif *",
        cr_city: "Ville",
        cr_city_ph: "Saisir la ville manuellement",
        cr_pass: "Mot de passe *",
        cr_conf_pass: "Confirmez le mot de passe *",
        cr_terms: "J'ai lu et j'accepte",
        cr_terms_use: "les conditions d'utilisation",
        cr_terms_privacy: "la politique de confidentialité",
        cr_terms_end: "de la plateforme Hirafi.",
        cr_btn: "Créer un nouveau compte",
        cr_have_account: "Vous avez déjà un compte ?",
        cr_login: "Se connecter",
        cr_artisan_link: "Vous êtes artisan ? Inscrivez-vous ici",
        // Client Workspace
        cw_espace_client: "ESPACE CLIENT",
        cw_welcome: "Bienvenue, ",
        cw_dashboard: "Mon Tableau de bord",
        cw_logout: "Déconnexion",
        cw_title: "Publier un nouveau projet",
        cw_desc: "Remplissez les détails ci-dessous pour recevoir des offres des meilleurs artisans qualifiés.",
        cw_proj_title: "Titre du Projet",
        cw_proj_title_ph: "Ex: Rénovation complète de la salle de bain",
        cw_category: "Catégorie",
        cw_cat_select: "Sélectionner une catégorie",
        cw_cat_carpentry: "Menuiserie",
        cw_cat_plumb: "Plomberie",
        cw_cat_elec: "Électricité",
        cw_cat_build: "Construction",
        cw_cat_paint: "Peinture",
        cw_cat_other: "Autre...",
        cw_budget: "Budget Estimé (MAD)",
        cw_optional: "(Optionnel)",
        cw_budget_ph: "Ex: 5000",
        cw_detail_desc: "Description Détaillée",
        cw_detail_desc_ph: "Décrivez votre besoin en détail...",
        cw_city: "Ville",
        cw_city_ph: "Ex: Casablanca",
        cw_neighborhood: "Quartier",
        cw_neighborhood_ph: "Ex: Maarif",
        cw_urgency: "Urgence",
        cw_urg_normal: "Normale",
        cw_urg_high: "Haute (Dès que possible)",
        cw_urg_urgent: "Urgente (Immédiat)",
        cw_urg_low: "Faible (Planifié pour plus tard)",
        cw_date: "Date souhaitée",
        cw_btn_pub: "Publier le Projet",
        cw_publishing: "Publication...",
        cw_pub_success: "Projet publié avec succès! Redirection...",
        cw_pub_err: "Erreur lors de la publication.",
        cw_srv_err: "Erreur serveur. Veuillez réessayer.",
        // Artisan Marketplace
        am_title: "HIRAFI PRO",
        am_welcome: "Bonjour, ",
        am_dashboard: "Mon Tableau de bord",
        am_logout: "Déconnexion",
        am_header_title: "Marketplace des Projets",
        am_header_desc: "Trouvez des opportunités qui correspondent à vos compétences à travers le Maroc.",
        am_smart_filters: "SMART FILTERS",
        am_search_ph: "Rechercher (ex: électricité, Casablanca)...",
        am_all_categories: "Toutes les catégories",
        am_my_spec: "★ Ma Spécialité",
        am_all_cities: "Toutes les villes",
        am_my_city: "📍 Ma Ville",
        am_empty_title: "Aucun projet disponible pour le moment",
        am_empty_desc: "Revenez plus tard ou modifiez vos filtres.",
        am_budget_est: "Budget Est.",
        am_to_discuss: "À discuter",
        am_mad: "MAD",
        am_location: "Localisation",
        am_client_id: "ID Client",
        am_verified: "Vérifié",
        am_proposals: "Propositions",
        am_received: " reçues",
        am_btn_details: "Détails",
        am_btn_offer: "Proposer Offre",
        am_urg_medium: "Normale",
        am_urg_high: "Haute",
        am_urg_urgent: "Urgente",
        am_urg_low: "Faible"
    }
};

// Global moroccan cities database (localizable)
window.moroccanCities = [
    { ar: "الدار البيضاء", fr: "Casablanca" },
    { ar: "الرباط", fr: "Rabat" },
    { ar: "مراكش", fr: "Marrakech" },
    { ar: "فاس", fr: "Fès" },
    { ar: "طنجة", fr: "Tanger" },
    { ar: "أكادير", fr: "Agadir" },
    { ar: "مكناس", fr: "Meknès" },
    { ar: "وجدة", fr: "Oujda" },
    { ar: "القنيطرة", fr: "Kénitra" },
    { ar: "تتوان", fr: "Tétouan" },
    { ar: "آسفي", fr: "Safi" },
    { ar: "المحمدية", fr: "Mohammedia" },
    { ar: "خريبكة", fr: "Khouribga" },
    { ar: "الجديدة", fr: "El Jadida" },
    { ar: "بني ملال", fr: "Béni Mellal" },
    { ar: "الناظور", fr: "Nador" },
    { ar: "تمارة", fr: "Témara" },
    { ar: "سلا", fr: "Salé" },
    { ar: "الرشيدية", fr: "Errachidia" },
    { ar: "خنيفرة", fr: "Khénifra" },
    { ar: "تيزنيت", fr: "Tiznit" },
    { ar: "العيون", fr: "Laâyoune" },
    { ar: "الداخلة", fr: "Dakhla" },
    { ar: "تارودانت", fr: "Taroudant" },
    { ar: "الصويرة", fr: "Essaouira" },
    { ar: "ورزازات", fr: "Ouarzazate" },
    { ar: "الحسيمة", fr: "Al Hoceïma" },
    { ar: "السعيدية", fr: "Saïdia" },
    { ar: "سطات", fr: "Settat" },
    { ar: "برشيد", fr: "Berrechid" },
    { ar: "بنسليمان", fr: "Benslimane" },
    { ar: "بركان", fr: "Berkane" },
    { ar: "العرائش", fr: "Larache" },
    { ar: "شفشاون", fr: "Chefchaouen" },
    { ar: "طانطان", fr: "Tan-Tan" },
    { ar: "كلميم", fr: "Guelmim" },
    { ar: "زاكورة", fr: "Zagora" },
    { ar: "وادي زم", fr: "Oued Zem" },
    { ar: "الخميسات", fr: "Khemisset" },
    { ar: "الصخيرات", fr: "Skhirate" },
    { ar: "القصر الكبير", fr: "Ksar El Kebir" },
    { ar: "سيدي قاسم", fr: "Sidi Kacem" },
    { ar: "تاونات", fr: "Taounate" },
    { ar: "اليوسفية", fr: "Youssoufia" },
    { ar: "مريرت", fr: "M'Rirt" }
];

// Global artisan specialized crafts (localizable)
window.artisanCrafts = [
    { ar: "سباكة", fr: "Plomberie" },
    { ar: "كهرباء", fr: "Électricité" },
    { ar: "صباغة", fr: "Peinture" },
    { ar: "نجارة", fr: "Menuiserie" },
    { ar: "بناء", fr: "Maçonnerie" },
    { ar: "حدادة", fr: "Ferronnerie" },
    { ar: "خياطة", fr: "Couture" },
    { ar: "صيانة السيارات", fr: "Mécanique auto" },
    { ar: "جبس وديكور", fr: "Plâtrerie" },
    { ar: "حلاقة وتجميل", fr: "Coiffure & Esthétique" },
    { ar: "حدائق ومساحات خضراء", fr: "Jardinage & Paysage" },
    { ar: "طبخ وحلويات", fr: "Cuisine & Traiteur" },
    { ar: "إصلاح الأجهزة المنزلية", fr: "Électroménager" },
    { ar: "ألومنيوم وزجاج", fr: "Aluminium & Vitrage" },
    { ar: "تكييف وتبريد", fr: "Climatisation" },
    { ar: "صناعة الفخار", fr: "Poterie & Céramique" },
    { ar: "زليج وفسيفساء", fr: "Zellige & Mosaïque" },
    { ar: "نقش على الخشب", fr: "Sculpture sur bois" },
    { ar: "نقش الجبس", fr: "Sculpture de plâtre" },
    { ar: "صناعة الجلد والدباغة", fr: "Maroquinerie & Tannerie" },
    { ar: "طرق وتنقش النحاس", fr: "Dinanderie & Gravure" },
    { ar: "صناعة الزرابي والنسيج", fr: "Tapis & Tissage" },
    { ar: "تركيب الرخام والسيراميك", fr: "Marbre & Carrelage" },
    { ar: "إصلاح الهواتف والإلكترونيات", fr: "Réparation Électronique" },
    { ar: "تنظيف وتطهير", fr: "Nettoyage & Services" },
    { ar: "تركيب الأبواب والنوافذ", fr: "Pose de portes et fenêtres" },
    { ar: "أعمال الأرضيات", fr: "Pose de sols" },
    { ar: "تركيب المطابخ", fr: "Installation de cuisines" },
    { ar: "تركيب الألواح الشمسية", fr: "Installation solaire" },
    { ar: "صيانة السخانات", fr: "Réparation de chauffe-eau" },
    { ar: "أعمال العزل الحراري والصوتي", fr: "Isolation thermique et acoustique" },
    { ar: "تركيب أنظمة الأمن والكاميرات", fr: "Installation de systèmes de sécurité" },
    { ar: "خدمات تكنولوجيا المعلومات والشبكات", fr: "Informatique & Réseaux" },
    { ar: "تصميم داخلي", fr: "Design d'intérieur" },
    { ar: "أعمال التشطيب الداخلي", fr: "Finitions intérieures" }
];

